//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ask
    {
        public int AskId { get; set; }
        public string AskTitle { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Context { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Answer { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsShown { get; set; }
    }
}
